/* eslint-disable class-methods-use-this */
class AppLoading extends HTMLElement {
  connectedCallback() {
    this.render();
  }

  render() {
    this.innerHTML = this.getTemplate();
  }

  getTemplate() {
    return `
        <div class="loadingio-spinner-ripple-hd9gcw4nfi8"><div class="ldio-w1byu8q9hlm">
        <div></div><div></div>
        </div></div>
        <style type="text/css">
        @keyframes ldio-w1byu8q9hlm {
        0% {
            top: 96px;
            left: 96px;
            width: 0;
            height: 0;
            opacity: 1;
        }
        100% {
            top: 18px;
            left: 18px;
            width: 156px;
            height: 156px;
            opacity: 0;
        }
        }.ldio-w1byu8q9hlm div {
        position: absolute;
        border-width: 4px;
        border-style: solid;
        opacity: 1;
        border-radius: 50%;
        animation: ldio-w1byu8q9hlm 1s cubic-bezier(0,0.2,0.8,1) infinite;
        }.ldio-w1byu8q9hlm div:nth-child(1) {
        border-color: #92201d;
        animation-delay: 0s;
        }
        .ldio-w1byu8q9hlm div:nth-child(2) {
        border-color: #c6302c;
        animation-delay: -0.5s;
        }
        .loadingio-spinner-ripple-hd9gcw4nfi8 {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: none;
        }
        .ldio-w1byu8q9hlm {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
        }
        .ldio-w1byu8q9hlm div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
        </style>         
        `;
  }
}

customElements.define('app-loading', AppLoading);
